### ISSUE TITLE
Allow to specify additional groups for jellyfin user

### ISSUE THREAD

**Issue by Paulomart** [sleepy-nols/ansible-jellyfin#17]
For hardware acceleration it is required to add the jellyfin user to the `render` group [[1]].

My workaround is to set the group after the role runs:

```yaml
- name: Add jellyfin to render group
  ansible.builtin.user:
    name: jellyfin
    group: render
    state: present
  notify: Restart jellyfin service
```

This causes unnecessary restarts of the service, since the role removes the group and then its added right back.

[1]: https://jellyfin.org/docs/general/post-install/transcoding/hardware-acceleration/intel#known-issues-and-limitations-on-linux
